import {
  Disposable,
  Webview,
  WebviewPanel,
  window,
  Uri,
  ViewColumn,
} from "vscode";
import { getUri } from "../utilities/getUri";
import { getNonce } from "../utilities/getNonce";
import * as fs from "fs";
import * as path from "path";

/**
 * This class manages the state and behavior of DockForge webview panels.
 */
export class DockForgePanel {
  public static currentPanel: DockForgePanel | undefined;
  private readonly _panel: WebviewPanel;
  private _disposables: Disposable[] = [];

  private constructor(panel: WebviewPanel, extensionUri: Uri) {
    this._panel = panel;

    this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

    this._panel.webview.html = this._getWebviewContent(
      this._panel.webview,
      extensionUri
    );

    // Webview → extension message handling
    this._setWebviewMessageListener(this._panel.webview);
  }

  public static render(extensionUri: Uri) {
    if (DockForgePanel.currentPanel) {
      DockForgePanel.currentPanel._panel.reveal(ViewColumn.One);
    } else {
      const panel = window.createWebviewPanel(
        "showDockForge",
        "DockForge",
        ViewColumn.One,
        {
          enableScripts: true,
          localResourceRoots: [
            Uri.joinPath(extensionUri, "out"),
            Uri.joinPath(extensionUri, "webview-ui/build"),
          ],
        }
      );

      DockForgePanel.currentPanel = new DockForgePanel(panel, extensionUri);
    }
  }

  public dispose() {
    DockForgePanel.currentPanel = undefined;
    this._panel.dispose();

    while (this._disposables.length) {
      const disposable = this._disposables.pop();
      if (disposable) {
        disposable.dispose();
      }
    }
  }

  private _getWebviewContent(webview: Webview, extensionUri: Uri) {
    const stylesUri = getUri(webview, extensionUri, [
      "webview-ui",
      "build",
      "assets",
      "index.css",
    ]);
    const scriptUri = getUri(webview, extensionUri, [
      "webview-ui",
      "build",
      "assets",
      "index.js",
    ]);

    const nonce = getNonce();

    return /*html*/ `
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta http-equiv="Content-Security-Policy"
            content="default-src 'none';
                     style-src ${webview.cspSource};
                     script-src 'nonce-${nonce}';">
          <link rel="stylesheet" type="text/css" href="${stylesUri}">
          <title>DockForge</title>
        </head>
        <body>
          <div id="root"></div>

          <script nonce="${nonce}">
            window.dockforgePage = "dockforge-home";
          </script>

          <script type="module" nonce="${nonce}" src="${scriptUri}"></script>
        </body>
      </html>
    `;
  }

  /**
   * Message listener: ONLY hello + insert to workspace
   */
  private _setWebviewMessageListener(webview: Webview) {
    webview.onDidReceiveMessage(
      async (message: { command?: string; type?: string }) => {
        const action = message.type ?? message.command;

        switch (action) {
          case "hello":
            window.showInformationMessage("Hello from DockForge");
            return;

          case "INSERT_TO_WORKSPACE": {
            // Ask user to select a folder
            const folders = await window.showOpenDialog({
              canSelectFiles: false,
              canSelectFolders: true,
              canSelectMany: false,
              openLabel: "Select folder to insert Dockerfile",
            });

            if (!folders || folders.length === 0) {
              window.showWarningMessage("No folder selected.");
              return;
            }

            const targetDir = folders[0].fsPath;
            const dockerfilePath = path.join(targetDir, "Dockerfile");

            const dockerfileContent = `# Generated by DockForge
FROM alpine:latest
CMD ["echo", "Hello from DockForge"]
`;

            try {
              fs.writeFileSync(dockerfilePath, dockerfileContent, {
                encoding: "utf8",
              });

              window.showInformationMessage(
                `Dockerfile created at:\n${dockerfilePath}`
              );
            } catch (error) {
              window.showErrorMessage(
                `Failed to create Dockerfile: ${
                  error instanceof Error ? error.message : String(error)
                }`
              );
            }

            return;
          }

          default:
            console.warn("Unknown webview message:", action);
        }
      },
      undefined,
      this._disposables
    );
  }
}