import {
  Disposable,
  Webview,
  WebviewPanel,
  window,
  Uri,
  ViewColumn,
} from "vscode";
import { getUri } from "../utilities/getUri";
import { getNonce } from "../utilities/getNonce";
import * as fs from "fs";
import * as path from "path";

/**
 * This class manages the state and behavior of DockForge webview panels.
 */
export class DockForgePanel {
  public static currentPanel: DockForgePanel | undefined;

  private readonly _panel: WebviewPanel;
  private readonly _disposables: Disposable[] = [];

  private constructor(panel: WebviewPanel, extensionUri: Uri) {
    this._panel = panel;

    this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

    this._panel.webview.html = this._getWebviewContent(
      this._panel.webview,
      extensionUri
    );

    this._setWebviewMessageListener(this._panel.webview);
  }

  /**
   * Render or reveal DockForge panel
   */
  public static render(extensionUri: Uri) {
    if (DockForgePanel.currentPanel) {
      DockForgePanel.currentPanel._panel.reveal(ViewColumn.One);
    } else {
      const panel = window.createWebviewPanel(
        "showDockForge",
        "DockForge",
        ViewColumn.One,
        {
          enableScripts: true,
          localResourceRoots: [
            Uri.joinPath(extensionUri, "out"),
            Uri.joinPath(extensionUri, "webview-ui/build"),
          ],
        }
      );

      DockForgePanel.currentPanel = new DockForgePanel(panel, extensionUri);
    }
  }

  public dispose() {
    DockForgePanel.currentPanel = undefined;
    this._panel.dispose();

    while (this._disposables.length) {
      this._disposables.pop()?.dispose();
    }
  }

  /**
   * Always generate:
   * Dockerfile, Dockerfile1, Dockerfile2, ...
   */
  private _getUniqueDockerfilePath(dir: string): string {
    let counter = 0;
    let filePath: string;

    do {
      const suffix = counter === 0 ? "" : counter.toString();
      filePath = path.join(dir, `Dockerfile${suffix}`);
      counter++;
    } while (fs.existsSync(filePath));

    return filePath;
  }

  /**
   * Generate Dockerfile content from stages
   */
  private _generateDockerfile(stages: any[]): string {
    const lines: string[] = [];
    lines.push("# Generated by DockForge", "");

    stages.forEach((stage, index) => {
      // FROM line (with optional AS)
      if (stage.stageName && stage.stageName.trim()) {
        lines.push(`FROM ${stage.baseImage} AS ${stage.stageName.trim()}`);
      } else {
        lines.push(`FROM ${stage.baseImage}`);
      }

      // Commands
      stage.commands.forEach((cmd: any) => {
        if (cmd.value && cmd.value.trim()) {
          lines.push(`${cmd.type} ${cmd.value}`);
        }
      });

      // Blank line between stages
      if (index < stages.length - 1) {
        lines.push("");
      }
    });

    return lines.join("\n") + "\n";
  }

  /**
   * Webview → Extension message handling
   */
  private _setWebviewMessageListener(webview: Webview) {
    webview.onDidReceiveMessage(
      async (message: { type?: string; payload?: any }) => {
        const action = message.type;

        switch (action) {
          case "hello":
            window.showInformationMessage("Hello from DockForge");
            return;

          case "INSERT_TO_WORKSPACE": {
            const warnings: string[] = message.payload?.warnings ?? [];
            const stages = message.payload?.stages ?? [];
            if (!stages || stages.length === 0) {
              window.showWarningMessage(
                "No stages found. Please add at least one stage before inserting a Dockerfile."
              );
              return;
            }
            // 1️⃣ Validation decision
            if (warnings.length > 0) {
              const choice = await window.showWarningMessage(
                `There are ${warnings.length} validation warning(s).`,
                { modal: true },
                "Keep Editing",
                "Insert Anyway"
              );

              if (choice !== "Insert Anyway") {
                return;
              }
            }

            // 2️⃣ Select target folder
            const folders = await window.showOpenDialog({
              canSelectFiles: false,
              canSelectFolders: true,
              canSelectMany: false,
              openLabel: "Select folder to insert Dockerfile",
            });

            if (!folders || folders.length === 0) {
              return;
            }

            const targetDir = folders[0].fsPath;

            // 3️⃣ Generate Dockerfile content
            const dockerfileContent = this._generateDockerfile(stages);

            // 4️⃣ Resolve unique filename
            const dockerfilePath = this._getUniqueDockerfilePath(targetDir);

            // 5️⃣ Write Dockerfile
            try {
              fs.writeFileSync(dockerfilePath, dockerfileContent, "utf8");
              window.showInformationMessage(
                `Dockerfile created successfully:\n${dockerfilePath}`
              );
            } catch (error) {
              window.showErrorMessage(
                `Failed to create Dockerfile: ${
                  error instanceof Error ? error.message : String(error)
                }`
              );
            }

            return;
          }

          default:
            console.warn("Unknown webview action:", action);
        }
      },
      undefined,
      this._disposables
    );
  }

  private _getWebviewContent(webview: Webview, extensionUri: Uri) {
    const stylesUri = getUri(webview, extensionUri, [
      "webview-ui",
      "build",
      "assets",
      "index.css",
    ]);
    const scriptUri = getUri(webview, extensionUri, [
      "webview-ui",
      "build",
      "assets",
      "index.js",
    ]);
    const nonce = getNonce();

    return /*html*/ `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'none';
                 style-src ${webview.cspSource};
                 script-src 'nonce-${nonce}';">
  <link rel="stylesheet" type="text/css" href="${stylesUri}">
  <title>DockForge</title>
</head>
<body>
  <div id="root"></div>

  <script nonce="${nonce}">
    window.dockforgePage = "dockforge-home";
  </script>

  <script type="module" nonce="${nonce}" src="${scriptUri}"></script>
</body>
</html>
`;
  }
}