import {
  Disposable,
  Webview,
  WebviewPanel,
  window,
  Uri,
  ViewColumn,
  workspace,
} from "vscode";
import { getUri } from "../utilities/getUri";
import { getNonce } from "../utilities/getNonce";
import { DockerfileData } from "../types/DockerfileData";
import { ensureDockerReady } from "../utilities/dockerCheck";
import { fetchDockerHubTags, searchDockerHubRepositories } from "../utilities/dockerHubApi";
import * as fs from "fs";
import * as path from "path";
import { spawn } from "child_process";
import * as os from "os";

/**
 * This class manages the state and behavior of DockForge webview panels.
 */
export class DockForgePanel {
  public static panels: Map<string, DockForgePanel> = new Map();
  private readonly _panel: WebviewPanel;
  private readonly _disposables: Disposable[] = [];
  private readonly _dockerfileId: string;
  private readonly _dockerfileName: string;
  private _data?: DockerfileData;
  private _onDataUpdate?: (id: string, data: DockerfileData) => void;


  private constructor(
    panel: WebviewPanel, 
    extensionUri: Uri, 
    dockerfileId: string, 
    dockerfileName: string,
    data?: DockerfileData,
    onDataUpdate?: (id: string, data: DockerfileData) => void
  ) {
    this._panel = panel;
    this._dockerfileId = dockerfileId;
    this._dockerfileName = dockerfileName;
    this._data = data;
    this._onDataUpdate = onDataUpdate;

    this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

    const htmlContent = this._getWebviewContent(
      this._panel.webview,
      extensionUri
    );
    
    // Debug: Log the HTML content
    console.log("[DockForge] Setting webview HTML for:", dockerfileName);
    console.log("[DockForge] HTML length:", htmlContent.length);
    
    this._panel.webview.html = htmlContent;

    // ✅ Correct place for all webview → extension logic
    this._setWebviewMessageListener(this._panel.webview);
  }

  /**
   * Renders the current webview panel if it exists otherwise a new webview panel
   * will be created and displayed.
   *
   * @param extensionUri The URI of the directory containing the extension.
   */
  public static render(
    extensionUri: Uri, 
    dockerfileId: string, 
    dockerfileName: string,
    data?: DockerfileData,
    onDataUpdate?: (id: string, data: DockerfileData) => void
  ) {
    const existingPanel = DockForgePanel.panels.get(dockerfileId);
    if (existingPanel) {
      // If panel already exists for Dockerfile, reveal and update data
      existingPanel._panel.reveal(ViewColumn.One);
      if (data) {
        existingPanel._data = data;
        existingPanel.sendDataToWebview();
      }
      return existingPanel;
    }

    const panel = window.createWebviewPanel(
      `dockforge-${dockerfileId}`,
      `DockForge - ${dockerfileName}`,
      ViewColumn.One,
      {
        enableScripts: true,
        localResourceRoots: [Uri.joinPath(extensionUri, "out"), Uri.joinPath(extensionUri, "webview-ui/build")],
        retainContextWhenHidden: true,
      }
    );

    const dockforgePanel = new DockForgePanel(panel, extensionUri, dockerfileId, dockerfileName, data, onDataUpdate);
    DockForgePanel.panels.set(dockerfileId, dockforgePanel);
    return dockforgePanel;
  }

  public static closePanel(dockerfileId: string) {
    const panel = DockForgePanel.panels.get(dockerfileId);
    if (panel) {
      panel.dispose();
    }
  }

  public static getPanel(dockerfileId: string): DockForgePanel | undefined {
    return DockForgePanel.panels.get(dockerfileId);
  }
  

  public dispose() {
    DockForgePanel.panels.delete(this._dockerfileId);

    // Dispose of the current webview panel
    this._panel.dispose();

    while (this._disposables.length) {
      this._disposables.pop()?.dispose();
    }
  }

  /**
   * Always generate:
   * Dockerfile, Dockerfile1, Dockerfile2, ...
   */
  private _getUniqueDockerfilePath(dir: string): string {
    let counter = 0;
    let filePath: string;

    do {
      const suffix = counter === 0 ? "" : counter.toString();
      filePath = path.join(dir, `Dockerfile${suffix}`);
      counter++;
    } while (fs.existsSync(filePath));

    return filePath;
  }

  /**
   * Generate Dockerfile content from stages
   */
  private _generateDockerfile(stages: any[]): string {
    const lines: string[] = [];
    lines.push("# Generated by DockForge", "");

    stages.forEach((stage, index) => {
      // FROM line (with optional AS)
      if (stage.stageName && stage.stageName.trim()) {
        lines.push(`FROM ${stage.baseImage} AS ${stage.stageName.trim()}`);
      } else {
        lines.push(`FROM ${stage.baseImage}`);
      }

      // Commands
      stage.commands.forEach((cmd: any) => {
        if (cmd.value && cmd.value.trim()) {
          lines.push(`${cmd.type} ${cmd.value}`);
        }
      });

      // Blank line between stages
      if (index < stages.length - 1) {
        lines.push("");
      }
    });

    return lines.join("\n") + "\n";
  }



  private _getWebviewContent(webview: Webview, extensionUri: Uri) {
    const stylesUri = getUri(webview, extensionUri, [
      "webview-ui",
      "build",
      "assets",
      "index.css",
    ]);
    const scriptUri = getUri(webview, extensionUri, [
      "webview-ui",
      "build",
      "assets",
      "index.js",
    ]);
    const nonce = getNonce();
    
    // Debug logging
    console.log("[DockForge] Extension URI:", extensionUri.toString());
    console.log("[DockForge] Styles URI:", stylesUri.toString());
    console.log("[DockForge] Script URI:", scriptUri.toString());
    console.log("[DockForge] CSP Source:", webview.cspSource);

    return /*html*/ `
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta http-equiv="Content-Security-Policy"
            content="default-src 'none';
                     style-src ${webview.cspSource} 'unsafe-inline';
                     script-src 'nonce-${nonce}' blob:;
                     worker-src ${webview.cspSource} blob:;
                     font-src ${webview.cspSource};
                     img-src ${webview.cspSource} https: data:;
                     connect-src https://hub.docker.com https://registry.hub.docker.com;">
          <link rel="stylesheet" type="text/css" href="${stylesUri}">
          <title>DockForge - ${this._dockerfileName}</title>
        </head>
        <body>
          <div id="root"></div>

          <script nonce="${nonce}">
            window.dockforgePage = "dockforge-home";
            window.dockerfileId = "${this._dockerfileId}";
            window.dockerfileName = "${this._dockerfileName}";
            window.dockerfileData = ${this._data ? JSON.stringify(this._data) : 'null'};
          </script>

          <script type="module" nonce="${nonce}" src="${scriptUri}"></script>
        </body>
      </html>
    `;
  }

  /**
   * ✅ Webview → Extension message handling
   */
  private _setWebviewMessageListener(webview: Webview) {
    webview.onDidReceiveMessage(
      async (message: { 
        command?: string; 
        type?: string; 
        payload?: any;
        data?: any;
        showNotification?: boolean;
        query?: string;
        repository?: string;
      }) => {
        // Support both `command` and `type` to avoid breaking changes
        const action = message.type ?? message.command;

        switch (action) {
          case "hello":
            window.showInformationMessage("Hello from DockForge");
            return;

          case "INSERT_TO_WORKSPACE": {
            const warnings: string[] = message.payload?.warnings ?? [];
            const stages = message.payload?.stages ?? [];
            if (!stages || stages.length === 0) {
              window.showWarningMessage(
                "No stages found. Please add at least one stage before inserting a Dockerfile."
              );
              return;
            }
            // 1️⃣ Validation decision
            if (warnings.length > 0) {
              const choice = await window.showWarningMessage(
                `There are ${warnings.length} validation warning(s).`,
                { modal: true },
                "Keep Editing",
                "Insert Anyway"
              );

              if (choice !== "Insert Anyway") {
                return;
              }
            }

            // 2️⃣ Select target folder
            const folders = await window.showOpenDialog({
              canSelectFiles: false,
              canSelectFolders: true,
              canSelectMany: false,
              openLabel: "Select folder to insert Dockerfile",
            });

            if (!folders || folders.length === 0) {
              return;
            }

            const targetDir = folders[0].fsPath;

            // 3️⃣ Generate Dockerfile content
            const dockerfileContent = this._generateDockerfile(stages);

            // 4️⃣ Resolve unique filename
            const dockerfilePath = this._getUniqueDockerfilePath(targetDir);

            // 5️⃣ Write Dockerfile
            try {
              fs.writeFileSync(dockerfilePath, dockerfileContent, "utf8");
              window.showInformationMessage(
                `Dockerfile created successfully:\n${dockerfilePath}`
              );
            } catch (error) {
              window.showErrorMessage(
                `Failed to create Dockerfile: ${
                  error instanceof Error ? error.message : String(error)
                }`
              );
            }

            return;
          }

          case "TEST_BUILD": {
            if (!(await ensureDockerReady())) return;

            const imageName: string = message.payload?.imageName || "my-image";
            const imageTag: string = message.payload?.imageTag || "latest";
            const stages = message.payload?.stages ?? [];

            // Clear UI and mark started
            this._postToWebview({ command: "testBuildStart", image: `${imageName}:${imageTag}`, ts: Date.now() });

            if (!stages || stages.length === 0) {
              this._postToWebview({
                command: "testBuildError",
                message: "No stages provided. Add at least one stage before testing build.",
                ts: Date.now(),
              });
              return;
            }

            // Pick a build context (workspace root if available, else ask user)
            let contextDir = workspace.workspaceFolders?.[0]?.uri.fsPath;

            if (!contextDir) {
              const picked = await window.showOpenDialog({
                canSelectFiles: false,
                canSelectFolders: true,
                canSelectMany: false,
                openLabel: "Select build context folder",
              });
              if (!picked || picked.length === 0) {
                this._postToWebview({ command: "testBuildError", message: "Build cancelled (no folder selected).", ts: Date.now() });
                return;
              }
              contextDir = picked[0].fsPath;
            }

            // Create a temp dockerfile
            const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "dockforge-"));
            const tempDockerfilePath = path.join(tempDir, "Dockerfile");

            try {
              const dockerfileContent = this._generateDockerfile(stages);
              fs.writeFileSync(tempDockerfilePath, dockerfileContent, "utf8");
            } catch (e) {
              const msg = e instanceof Error ? e.message : String(e);
              this._postToWebview({ command: "testBuildError", message: `Failed to write temp Dockerfile: ${msg}`, ts: Date.now() });
              return;
            }

            // Build args
            const tag = `${imageName}:${imageTag}`;
            const args = ["build", "-f", tempDockerfilePath, "-t", tag, contextDir];

            this._postToWebview({ command: "testBuildLog", kind: "stdout", line: `docker ${args.join(" ")}`, ts: Date.now() });

            const exitCode = await this._runDockerBuildAndStreamLogs(args);

            if (exitCode === 0) {
              this._postToWebview({ command: "testBuildDone", ok: true, image: tag, ts: Date.now() });
            } else {
              this._postToWebview({ command: "testBuildDone", ok: false, image: tag, exitCode, ts: Date.now() });
            }

            // Cleanup temp dockerfile
            try {
              fs.rmdirSync(tempDir, { recursive: true });
            } catch {}

            return;
          }

          case "BUILD_IMAGE": {
            if (!(await ensureDockerReady())) return;

            // TODO:
            // Implement docker build image logic here
            window.showInformationMessage(
              "Docker is ready. Build Image can proceed."
            );
            return;
          }

          case "RUN_CONTAINER": {
            if (!(await ensureDockerReady())) return;

            // TODO:
            // Implement docker run container logic here
            window.showInformationMessage(
              "Docker is ready. Run Container can proceed."
            );
            return;
          }
          
          case "saveDockerfileData":
            // Save Dockerfile data
            if (message.data && this._onDataUpdate) {
              this._data = message.data;
              try {
                this._onDataUpdate(this._dockerfileId, message.data);
                // Only show notification if explicitly requested (manual save)
                if (message.showNotification) {
                  window.showInformationMessage(`Saved: ${this._dockerfileName}`);
                }
              } catch (error) {
                const errorMessage = error instanceof Error ? error.message : String(error);
                window.showErrorMessage(`Failed to save ${this._dockerfileName}: ${errorMessage}`);
                console.error(`Error saving Dockerfile data for ${this._dockerfileId}:`, error);
              }
            }
            return;
          
          case "requestDockerfileData":
            // Send current data to webview
            this.sendDataToWebview();
            return;

          case "dockerHubSearch": {
            const query =
              message.payload?.query ??
              message.data?.query ??
              message.query ??
              "";

            if (!query || typeof query !== "string") {
              this._panel.webview.postMessage({
                command: "dockerHubSearchResults",
                results: [],
              });
              return;
            }

            try {
              const results = await searchDockerHubRepositories(query, 15);
              this._panel.webview.postMessage({
                command: "dockerHubSearchResults",
                query,
                results,
              });
            } catch (error) {
              const messageText =
                error instanceof Error ? error.message : String(error);
              this._panel.webview.postMessage({
                command: "dockerHubError",
                message: messageText,
              });
            }
            return;
          }

          case "dockerHubFetchTags": {
            const repository =
              message.payload?.repository ??
              message.data?.repository ??
              message.repository ??
              "";

            if (!repository || typeof repository !== "string") {
              return;
            }

            try {
              const tags = await fetchDockerHubTags(repository, 30);
              this._panel.webview.postMessage({
                command: "dockerHubTagsResult",
                repository,
                tags,
              });
            } catch (error) {
              const messageText =
                error instanceof Error ? error.message : String(error);
              this._panel.webview.postMessage({
                command: "dockerHubError",
                message: messageText,
              });
            }
            return;
          }

          default:
            console.warn("Unknown webview message:", message);
        }
      },
      undefined,
      this._disposables
    );
  }

  /**
   * Send data to webview
   */
  private sendDataToWebview() {
    if (this._data) {
      this._panel.webview.postMessage({
        command: "loadDockerfileData",
        data: this._data
      });
    }
  }
  private _postToWebview(payload: any) {
  this._panel.webview.postMessage(payload);
}

private _runDockerBuildAndStreamLogs(args: string[]) {
  return new Promise<number>((resolve) => {
    const proc = spawn("docker", args, { shell: false });

    const send = (kind: "stdout" | "stderr", chunk: any) => {
      const text = chunk.toString();
      // Split to lines so UI can append nicely
      text.split(/\r?\n/).forEach((line: string) => {
        if (!line.trim()) return;
        this._postToWebview({
          command: "testBuildLog",
          kind,
          line,
          ts: Date.now(),
        });
      });
    };

    proc.stdout.on("data", (d) => send("stdout", d));
    proc.stderr.on("data", (d) => send("stderr", d));

    proc.on("close", (code) => resolve(code ?? 0));
    proc.on("error", (err) => {
      this._postToWebview({
        command: "testBuildLog",
        kind: "stderr",
        line: `Failed to start docker: ${err.message}`,
        ts: Date.now(),
      });
      resolve(1);
    });
  });
}
}
